/**
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Same technique as alphabet array of 26.

**/

class Solution {
public:
    char findTheDifference(string s, string t) 
    {
        int a[26];
        memset(a,0,sizeof(a));
        for(auto i : s)
            a[i-'a']++;
        
        for(auto x : t)
        {
            if(a[x-'a']==0)
                return x;
            else
                a[x-'a']--;
        }
        return 'c';
    }
};
